server:
  port: 8888
  compression.enabled: true

  tomcat:
    max-threads: 1000
    max-connections: 10000
    min-spare-threads: 5
    uri-encoding: UTF-8

  servlet:
    session:
      cookie:
        http-only: true
        domain: /
spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      maxActive: 8
      testOnBorrow: true
      validationQuery: SELECT 1
    aliYun:
      url: jdbc:mysql://**********/aliyun?serverTimezone=Asia/Shanghai
      username: root
      password: root
    paper:
      url: jdbc:mysql://**********/paper?serverTimezone=Asia/Shanghai
      username: root
      password: root.


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis-plus:
  config-location: 'classpath:/mapper/**/*Mapper.xml'
